### ISSUE TITLE
可以标注一下，init函数也可以用来随时切换语言

### ISSUE THREAD

**Issue by zhbzhbzhbz** [ZOMAKE/jquery.i18n#1]
本来想改您的代码，后来试了下动态调用Init函数也可以起到切换语言的效果

**Comment by zhbzhbzhbz** [comment]
另外判断val()==""其实没必要我觉得，否则中间还得加些文字

**Comment by T-baby** [comment]
谢谢您的反馈，不知道您说的val()==""是哪一行呢？

**Comment by zhbzhbzhbz** [comment]
66和71行

**Comment by T-baby** [comment]
我是觉得，如果value为空的话就不应该进行翻译操作。所以当时加了判断。对于需要翻译很多的网页和较大的翻译文件来说，可以稍稍提升性能。
